export const REFRESHTOKEN = 'REFRESHTOKEN';
export const ACCESSTOKEN = 'ACCESSTOKEN';

export const CREATE = 'CREATE';
export const READ = 'READ';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const INVALIDATE = 'INVALIDATE';

const REFRESH_QUERY_KEY = {
  READ_ACCESSTOKEN_WITH_REFRESHTOKEN: [READ, ACCESSTOKEN, REFRESHTOKEN],
  CREATE_ACCESSTOKEN_WITH_REFRESHTOKEN: [CREATE, ACCESSTOKEN, REFRESHTOKEN],
  READ_INVALIDATE_REFRESHTOKEN: [READ, INVALIDATE, REFRESHTOKEN],
};
export default REFRESH_QUERY_KEY;
