export const CREATE = 'CREATE';
export const READ = 'READ';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';

export const PROPERTIES = 'PROPERTIES';

export const ROLES = 'ROLES';
export const QUESTIONS = 'QUESTIONS';
export const FIELDS = 'FIELDS';

const PROPERTIES_QUERY_KEY = {
  READ_PROPERTIES_ROLES: [READ, PROPERTIES, ROLES],
  READ_PROPERTIES_QUESTIONS: [READ, PROPERTIES, QUESTIONS],
  READ_PROPERTIES_FIELDS: [READ, PROPERTIES, FIELDS],
  CREATE_PROPERTIES_ROLES: [CREATE, PROPERTIES, ROLES],
  CREATE_PROPERTIES_QUESTIONS: [CREATE, PROPERTIES, QUESTIONS],
};
export default PROPERTIES_QUERY_KEY;
